# Generated by Django 3.2.3 on 2021-05-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='customlink',
            name='description',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
