# Generated by Django 3.2.3 on 2021-05-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customlink_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customlink',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
