# Generated by Django 3.2.3 on 2021-06-22 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_customlink_animation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customlink',
            name='animation',
        ),
    ]
