# Generated by Django 3.2.3 on 2021-06-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_customlink_animation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customlink',
            name='animation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
