# Generated by Django 3.2.3 on 2021-06-23 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_customlink_animation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customlink',
            name='animation',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='account.linkanimation'),
        ),
    ]
