# Generated by Django 3.2.3 on 2021-06-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_customlink_animation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customlink',
            name='position',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
