# Generated by Django 3.2.3 on 2021-06-26 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customlink',
            name='animation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.linkanimation'),
        ),
    ]
