# Generated by Django 3.2.5 on 2021-07-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_customlink_animation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='premium_links_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
