# Generated by Django 3.2.5 on 2021-07-28 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0021_profile_premium_links_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumCustomLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('description', models.CharField(blank=True, max_length=220)),
                ('url', models.URLField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='premium_link_img')),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.IntegerField(blank=True, default=0)),
                ('animation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.linkanimation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
