# Generated by Django 3.2.5 on 2021-08-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_premiumcustomlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
