# Generated by Django 3.2.3 on 2021-08-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_alter_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customlink',
            name='display_as_yt_embed',
            field=models.BooleanField(default=False),
        ),
    ]
