# Generated by Django 3.2.3 on 2021-10-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_customlink_display_as_yt_embed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linkshub_label',
            field=models.BooleanField(default=True),
        ),
    ]
