# Generated by Django 3.2.3 on 2021-10-29 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_profile_linkshub_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='linkshub_label',
        ),
    ]
