# Generated by Django 3.2.3 on 2022-01-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_premiumcustomlink_display_as_yt_embed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_premium_links',
            field=models.BooleanField(default=True),
        ),
    ]
