# Generated by Django 3.2.3 on 2022-01-28 16:50

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_profile_display_premium_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='profile_pic'),
        ),
    ]
