# Generated by Django 3.2.3 on 2021-06-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210620_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileview',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
    ]
