# Generated by Django 3.2.3 on 2021-06-30 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_platformclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileview',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
