# Generated by Django 3.2.5 on 2021-07-03 09:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_profileview_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkclick',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
