# Generated by Django 3.2.5 on 2021-07-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_platformclick_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileview',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profileview',
            name='country',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
