# Generated by Django 3.2.5 on 2021-07-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20210719_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkclick',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='linkclick',
            name='country',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
