# Generated by Django 3.2.5 on 2021-07-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20210719_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileview',
            name='device',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
