# Generated by Django 3.2.3 on 2021-05-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0004_auto_20210524_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundtheme',
            name='type',
            field=models.CharField(blank=True, choices=[('color', 'color'), ('gradient', 'gradient'), ('moving_gradient', 'moving_gradient')], max_length=100),
        ),
    ]
