# Generated by Django 3.2.3 on 2021-05-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0005_backgroundtheme_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backgroundtheme',
            name='class_name',
        ),
        migrations.AddField(
            model_name='backgroundtheme',
            name='background_color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='backgroundtheme',
            name='font_color',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
