# Generated by Django 3.2.3 on 2021-05-28 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0009_buttontheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertheme',
            name='button_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appearance.buttontheme'),
        ),
    ]
