# Generated by Django 3.2.3 on 2021-05-28 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0011_custombuttontheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertheme',
            name='custom_button_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appearance.custombuttontheme'),
        ),
    ]
