# Generated by Django 3.2.3 on 2021-05-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0012_usertheme_custom_button_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertheme',
            name='button_fill',
            field=models.CharField(blank=True, choices=[('filled', 'filled'), ('transparent', 'transparent')], max_length=120),
        ),
    ]
