# Generated by Django 3.2.3 on 2021-05-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0013_usertheme_button_fill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertheme',
            name='button_fill',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
