# Generated by Django 3.2.3 on 2021-06-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0014_alter_usertheme_button_fill'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertheme',
            name='button_outline',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
