# Generated by Django 3.2.3 on 2021-06-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0015_usertheme_button_outline'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertheme',
            name='button_shadow',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
