# Generated by Django 3.2.3 on 2021-08-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0016_usertheme_button_shadow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custombackgroundtheme',
            name='background_color',
            field=models.CharField(max_length=400),
        ),
    ]
