# Generated by Django 3.2.3 on 2021-10-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0018_custombackgroundtheme_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertheme',
            name='linkshub_label',
            field=models.BooleanField(default=True),
        ),
    ]
