# Generated by Django 3.2.3 on 2021-12-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0002_premiumfreetrial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='purchase_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
