# Generated by Django 3.2.3 on 2021-12-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0003_customer_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
