# Generated by Django 3.2.3 on 2021-12-18 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0004_alter_customer_purchase_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='purchase_date',
        ),
    ]
